run:
  concurrency: 8
  deadline: 1m
  issues-exit-code: 1
  modules-download-mode: readonly
  tests: true
  skip-dirs:
    - test
    - migrations
#  skip-files:

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: false
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - nakedret
    - gosimple
    - goconst
    - unconvert
    - varcheck
    - deadcode
    - gocritic
    - prealloc
    - exportloopref
  fast: false

issues:
  exclude-rules:
    #   исключены правила, указывающие на аббревиатуры в именах (пример ошибки линтера: Id => ID)
    - linters:
        - revive
      text: "var.*should|type.*should|struct field.*should|method.*should|func.*should|const.*should|type.*consider|func.*consider"
    - linters:
        - revive
      text: "error strings should not be capitalized or end with punctuation or a newline"
